name: CI

on:
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '15 1 * * *' # Nightly at 01:15

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check Spelling
        uses: crate-ci/typos@02ea592e44b3a53c302f697cddca7641cd051c3d # v1.45.0
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check Format
        run: crystal tool format --check
  coding_standards:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # Workaround https://github.com/amberframework/micrate/issues/87
      - name: Install Lib Dependencies
        run: apt update && apt upgrade -y && apt install -y libsqlite3-dev
      - name: Install Dependencies
        run: shards install
      - name: Ameba
        run: ./bin/ameba
  test:
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: blog_test_user
          POSTGRES_PASSWORD: 'mYAw3s0meB!og'
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 2s --health-timeout 10s --health-retries 5
      mercure-hub:
        image: dunglas/mercure
        env:
          SERVER_NAME: ':80' # Disable HTTPS for local dev
          MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
          MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
          MERCURE_EXTRA_DIRECTIVES: |
            cors_origins http://localhost:3000 # Allow Athena Server
        ports:
          - 80:80
        options: >-
          --health-cmd pg_isready --health-interval 2s --health-timeout 10s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        crystal:
          - latest
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt install -y libmagic-dev
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@d8ef131ecec0352ce0e39b81b0a6d95def58fe2f # v1.9.2
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install Dependencies
        run: shards install --skip-postinstall --skip-executables
      - name: Specs
        run: crystal spec -Dstrict_multi_assign --order=random --error-on-warnings
